### ISSUE TITLE
navbar.html

### ISSUE THREAD

**Issue by anshumanv** [Monal5031/WebpageProject-IntroToIT#3]
Will initialize the start index.html page.
We will have a single page so called index.html
All the works to be  updated will be done in a separate file and after testing will be collaborated in index.html file.
Do let me know if there are any further issues

**Comment by Monal5031** [comment]
Create a separate dir for html files keep the stable files in there.
Make 2 files infront
Index,html will contain the start page of the project while test.html will show the recent testing you have done.

**Comment by Monal5031** [comment]
Fixed in #7
