### ISSUE TITLE
BG image request

### ISSUE THREAD

**Issue by anshumanv** [Monal5031/WebpageProject-IntroToIT#5]
Is it possible to have a collage created in convenient time of about 10-12 geek images to be used as a background of the index.html page ? 
If not we need to pick a gradient or pre-built stuff as our background.

**Comment by Monal5031** [comment]
@Anshuman-Verma Yeah it is nice thought.
send a PR for it after adding it in Readme.md

**Comment by Monal5031** [comment]
Not required anymore!
