### ISSUE TITLE
Separate .html & .css PR feasibility

### ISSUE THREAD

**Issue by anshumanv** [Monal5031/WebpageProject-IntroToIT#6]
Will not be creating separate PR's for .html and .css file, will only send a PR on a feature once tested and added which will include both .html and .css changes which can be reviewed both at the same time.

**Comment by Monal5031** [comment]
Okay @Anshuman-Verma Just make sure you have tested it correctly before sending a PR

**Comment by Monal5031** [comment]
Closing this as it is decided to send both files in same PR
